### PR TITLE
Fixing public-access-blocking on buckets created during runtime

### LINKED ISSUE #31: Feature request: support provider.deploymentBucket.blockPublicAccess
Hi, thanks for your work putting this project together. Much appreciated

It appears `serverless-deployment-bucket` doesn't pick up on the `provider.deploymentBucket.blockPublicAccess` key in serverless.yml. I realize it's possible to [set an exact bucket policy](https://github.com/MikeSouza/serverless-deployment-bucket/issues/15#issuecomment-674872243), but it seems likely that a common use case is to want to block all public access, and when not using this plugin that can be done with just:

```yml
provider:
  deploymentBucket:
    blockPublicAccess: true
```

For reference, here's how this was [implemented in serverless core](https://github.com/serverless/serverless/pull/6779)

### PR DESCRIPTION
**Pull request by jdrydn**
Fixes #31

### CODE REVIEW

**Comment by joenye** [comment]
Thanks for the fix! When can we get this merged? Our team is currently awaiting on this fix.

**Review by mikesouza — APPROVED** [review]

**Comment by MikeSouza** [comment]
@joenye I cut a new release v1.4.1.

**Comment by ashishjullia** [comment]
@MikeSouza I'm using the following serverless.yml but it is not working for me:

```
service: test-jj

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: test-jj-dev-serverlessdeploymentbucket
    serverSideEncryption: AES256
    
custom:
  deploymentBucket:
    versioning: true
    accelerate: true
    blockPublicAccess: true
    tags:
      - Key: Environment
        Value: production

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: atest-jj-dev-serverlessdeploymentbucket-new

```

`blockPublicAccess: true` not working + I'm getting the following error as well - I do have "Administrator" access for the aws user.

image

**Comment by ashishjullia** [comment]
For future people, I had to remove `accelerate: true`.

**Pull request merged**
