### PR TITLE
Skip bucket creation on serverless package

### LINKED ISSUE #6: bucket is created when using sls package
When running `sls package`, it triggers `Creating deployment bucket` which actually creates AWS resources. The creation of the bucket should only happen on deploy

### PR DESCRIPTION
**Pull request by onhate**
fix #6

### CODE REVIEW

**Comment by onhate** [comment]
@MikeSouza please let me know your thoughts, I am using this changed version on my project using .serverless_plugins folder and it is working fine so far.

**Comment by onhate** [comment]
@MikeSouza I don't get why coveralls is complaining, when I run it locally I get 100% `¯\_(ツ)_/¯`

**Comment by onhate** [comment]
got it :) fixed

**Comment by onhate** [comment]
@MikeSouza ?

**Comment by MikeSouza** [comment]
Sorry. It’s been a stressful month. I’ll try to take a look this week.

**Comment by MikeSouza** [comment]
@onhate I released a new version `1.1.2` with your fix. Thanks.

**Pull request merged**
